### ISSUE TITLE
The inconsistent performance on COLLAB dataset

### ISSUE THREAD

**Issue by ZhuYun97** [THUDM/GraphMAE#16]
Thanks for your fabulous codes, but I meet some problems while reproducing. After running 5 runs(`sh scripts/run_graph.sh COLLAB 0` using seed: 0,1,2,3,4), the performance on COLLAB dataset is 78.78±0.46 which remains a large margin with the reported value(80.32±0.46). 
I check the model configuration in the Appendix and find the hidden size of GIN is 512(but 256 in the [config.yaml](https://github.com/THUDM/GraphMAE/blob/1be594160bb7c1fde0d16ced6af1e88b53612e49/configs.yml#L255)). After changing the hidden size to 512, the performance(78.70±0.32) is still inferior to the paper. 
Is there anything I missing? hope for your reply.

**Comment by THINK2TRY** [comment]
@ZhuYun97 Thanks for your interest. The scaling coefficient `alpha_l` should be set to 1 in COLLAB, while it is 2 by default now. Sorry to miss this hyper-parameter in configs.yml. We have updated `configs.yml`. Hope this help.

**Comment by ZhuYun97** [comment]
Thanks for your instant reply.

**Comment by ZhuYun97** [comment]
Sorry to bother you again. The performance on MUTAG dataset is 86.47±1.81, but I find that all the hyperparameters are the same with Appendix. Is there any other things I should change?

**Comment by ZhuYun97** [comment]
I use the latest `config.yml`. And I run on NVIDIA 3090(I also test on NVIDIA 1080Ti, but get similar results).
```
MUTAG:
  num_hidden: 32
  num_layers: 5
  lr: 0.0005
  weight_decay: 0.00
  mask_rate: 0.75
  drop_edge_rate: 0.0
  max_epoch: 20
  encoder: gin
  decoder: gin
  activation: prelu
  loss_fn: sce
  scheduler: False  
  pooling: sum
  batch_size: 64
  alpha_l: 2
  replace_rate: 0.1
  norm: batchnorm
  in_drop: 0.2
  attn_drop: 0.1
  alpha_l: 2
```
